import type { Parsha } from './types';

export const parshiot: Parsha[] = [
  { slug: 'bereshit', name: 'בראשית' },
  { slug: 'noach', name: 'נח' },
  { slug: 'lech-lecha', name: 'לך-לך' },
  { slug: 'vayeira', name: 'וירא' },
  { slug: 'chayei-sarah', name: 'חיי שרה' },
  { slug: 'toldot', name: 'תולדות' },
  { slug: 'vayetzei', name: 'ויצא' },
  { slug: 'vayishlach', name: 'וישלח' },
  { slug: 'vayeshev', name: 'וישב' },
  { slug: 'miketz', name: 'מקץ' },
  { slug: 'vayigash', name: 'ויגש' },
  { slug: 'vayechi', name: 'ויחי' },
  { slug: 'shemot', name: 'שמות' },
  { slug: 'vaera', name: 'וארא' },
  { slug: 'bo', name: 'בא' },
  { slug: 'beshalach', name: 'בשלח' },
  { slug: 'yitro', name: 'יתרו' },
  { slug: 'mishpatim', name: 'משפטים' },
  { slug: 'terumah', name: 'תרומה' },
  { slug: 'tetzaveh', name: 'תצוה' },
  { slug: 'ki-tisa', name: 'כי תשא' },
  { slug: 'vayakhel', name: 'ויקהל' },
  { slug: 'pekudei', name: 'פקודי' },
  { slug: 'vayikra', name: 'ויקרא' },
  { slug: 'tzav', name: 'צו' },
  { slug: 'shmini', name: 'שמיני' },
  { slug: 'tazria', name: 'תזריע' },
  { slug: 'metzora', name: 'מצורע' },
  { slug: 'acharei-mot', name: 'אחרי מות' },
  { slug: 'kedoshim', name: 'קדושים' },
  { slug: 'emor', name: 'אמור' },
  { slug: 'behar', name: 'בהר' },
  { slug: 'bechukotai', name: 'בחוקותי' },
  { slug: 'bamidbar', name: 'במדבר' },
  { slug: 'naso', name: 'נשא' },
  { slug: 'behaalotcha', name: 'בהעלותך' },
  { slug: 'shlach', name: 'שלח' },
  { slug: 'korach', name: 'קרח' },
  { slug: 'chukat', name: 'חקת' },
  { slug: 'balak', name: 'בלק' },
  { slug: 'pinchas', name: 'פינחס' },
  { slug: 'matot', name: 'מטות' },
  { slug: 'masei', name: 'מסעי' },
  { slug: 'devarim', name: 'דברים' },
  { slug: 'vaetchanan', name: 'ואתחנן' },
  { slug: 'eikev', name: 'עקב' },
  { slug: 'reeh', name: 'ראה' },
  { slug: 'shoftim', name: 'שופטים' },
  { slug: 'ki-tetzei', name: 'כי תצא' },
  { slug: 'ki-tavo', name: 'כי תבוא' },
  { slug: 'nitzavim', name: 'ניצבים' },
  { slug: 'vayelech', name: 'וילך' },
  { slug: 'haazinu', name: 'האזינו' },
  { slug: 'vezot-haberakhah', name: 'וזאת הברכה' },
];
