
import type { Chumash, Parsha } from "./types";

export function getStaticParshiotData() {
    const chumashim: Chumash[] = [
        { id: 'genesis', name: 'בראשית', order: 1 },
        { id: 'exodus', name: 'שמות', order: 2 },
        { id: 'leviticus', name: 'ויקרא', order: 3 },
        { id: 'numbers', name: 'במדבר', order: 4 },
        { id: 'deuteronomy', name: 'דברים', order: 5 },
    ];

    const parshiot: Parsha[] = [
      { id: 'bereshit', name: 'בראשית', chumashId: 'genesis' },
      { id: 'noach', name: 'נח', chumashId: 'genesis' },
      { id: 'lech-lecha', name: 'לך-לך', chumashId: 'genesis' },
      { id: 'vayeira', name: 'וירא', chumashId: 'genesis' },
      { id: 'chayei-sarah', name: 'חיי שרה', chumashId: 'genesis' },
      { id: 'toldot', name: 'תולדות', chumashId: 'genesis' },
      { id: 'vayetzei', name: 'ויצא', chumashId: 'genesis' },
      { id: 'vayishlach', name: 'וישלח', chumashId: 'genesis' },
      { id: 'vayeshev', name: 'וישב', chumashId: 'genesis' },
      { id: 'miketz', name: 'מקץ', chumashId: 'genesis' },
      { id: 'vayigash', name: 'ויגש', chumashId: 'genesis' },
      { id: 'vayechi', name: 'ויחי', chumashId: 'genesis' },
      { id: 'shemot', name: 'שמות', chumashId: 'exodus' },
      { id: 'vaera', name: 'וארא', chumashId: 'exodus' },
      { id: 'bo', name: 'בא', chumashId: 'exodus' },
      { id: 'beshalach', name: 'בשלח', chumashId: 'exodus' },
      { id: 'yitro', name: 'יתרו', chumashId: 'exodus' },
      { id: 'mishpatim', name: 'משפטים', chumashId: 'exodus' },
      { id: 'terumah', name: 'תרומה', chumashId: 'exodus' },
      { id: 'tetzaveh', name: 'תצוה', chumashId: 'exodus' },
      { id: 'ki-tisa', name: 'כי תשא', chumashId: 'exodus' },
      { id: 'vayakhel', name: 'ויקהל', chumashId: 'exodus' },
      { id: 'pekudei', name: 'פקודי', chumashId: 'exodus' },
      { id: 'vayikra', name: 'ויקרא', chumashId: 'leviticus' },
      { id: 'tzav', name: 'צו', chumashId: 'leviticus' },
      { id: 'shmini', name: 'שמיני', chumashId: 'leviticus' },
      { id: 'tazria', name: 'תזריע', chumashId: 'leviticus' },
      { id: 'metzora', name: 'מצורע', chumashId: 'leviticus' },
      { id: 'acharei-mot', name: 'אחרי מות', chumashId: 'leviticus' },
      { id: 'kedoshim', name: 'קדושים', chumashId: 'leviticus' },
      { id: 'emor', name: 'אמור', chumashId: 'leviticus' },
      { id: 'behar', name: 'בהר', chumashId: 'leviticus' },
      { id: 'bechukotai', name: 'בחוקותי', chumashId: 'leviticus' },
      { id: 'bamidbar', name: 'במדבר', chumashId: 'numbers' },
      { id: 'naso', name: 'נשא', chumashId: 'numbers' },
      { id: 'behaalotcha', name: 'בהעלותך', chumashId: 'numbers' },
      { id: 'shlach', name: 'שלח', chumashId: 'numbers' },
      { id: 'korach', name: 'קרח', chumashId: 'numbers' },
      { id: 'chukat', name: 'חקת', chumashId: 'numbers' },
      { id: 'balak', name: 'בלק', chumashId: 'numbers' },
      { id: 'pinchas', name: 'פינחס', chumashId: 'numbers' },
      { id: 'matot', name: 'מטות', chumashId: 'numbers' },
      { id: 'masei', name: 'מסעי', chumashId: 'numbers' },
      { id: 'devarim', name: 'דברים', chumashId: 'deuteronomy' },
      { id: 'vaetchanan', name: 'ואתחנן', chumashId: 'deuteronomy' },
      { id: 'eikev', name: 'עקב', chumashId: 'deuteronomy' },
      { id: 'reeh', name: 'ראה', chumashId: 'deuteronomy' },
      { id: 'shoftim', name: 'שופטים', chumashId: 'deuteronomy' },
      { id: 'ki-tetzei', name: 'כי תצא', chumashId: 'deuteronomy' },
      { id: 'ki-tavo', 'name': 'כי תבוא', chumashId: 'deuteronomy' },
      { id: 'nitzavim', name: 'ניצבים', chumashId: 'deuteronomy' },
      { id: 'vayelech', name: 'וילך', chumashId: 'deuteronomy' },
      { id: 'haazinu', name: 'האזינו', chumashId: 'deuteronomy' },
      { id: 'vezot-haberakhah', name: 'וזאת הברכה', chumashId: 'deuteronomy' },
    ];
    return { chumashim, parshiot };
}
